package com.luminastreams.tv.domain.model

import androidx.compose.runtime.Immutable

// ── Movie ──────────────────────────────────────────────────────────────────────
@Immutable
data class Movie(
    val id: String,
    val title: String,
    val backdropUrl: String,
    val posterUrl: String,
    val overview: String,
    val rating: Float,
    val year: Int = 0,
    val genre: String = "פעולה",
    val mediaType: String = "movie",
    val genreIds: List<Int> = emptyList(),
    val is4K: Boolean = false,
    val resolutionBadge: String = "1080p",
    val progress: Float? = null
)

// ── SearchResult ──────────────────────────────────────────────────────────────────
enum class MediaType(val label: String, val hebrewPlural: String) {
    MOVIE("סרט", "סרטים"),
    TV_SHOW("סדרה", "סדרות"),
    PERSON("שחקן", "שחקנים")
}

@Immutable
data class SearchResult(
    val id: String,
    val title: String,
    val posterUrl: String,
    val backdropUrl: String? = null,
    val logoUrl: String? = null,
    val type: MediaType,
    val rating: Float = 0f,
    val releaseYear: String = "",
    val overview: String = "",
    val matchScore: Int = 0,
    val dominantColor: String? = null
)

// ── StreamSource ──────────────────────────────────────────────────────────────────
data class StreamSource(
    val id: String,
    val groupName: String,
    val filename: String,
    val sizeGb: Double,
    val seeders: Int,
    val resolution: String,
    val codec: String,
    val audioFormat: String,
    val isCached: Boolean,
    val isDV: Boolean,
    val isHDR10: Boolean,
    val hasBuiltInSubs: Boolean,
    val infoHash: String? = null
)

// ── Subtitle ───────────────────────────────────────────────────────────────────────
@Immutable
data class Subtitle(
    val language: String,
    val url: String,
    val isAutoGenerated: Boolean
)
