package com.luminastreams.tv.domain.model

import androidx.compose.runtime.Immutable

// ── Movie ────────────────────────────────────────────────────────────────────
@Immutable
data class Movie(
    val id: String,
    val title: String,
    val backdropUrl: String,
    val posterUrl: String,
    val overview: String,
    val rating: Float,
    val year: Int = 0,
    val genre: String = "פעולה",
    val mediaType: String = "movie",
    val genreIds: List<Int> = emptyList(),
    val is4K: Boolean = false,
    val resolutionBadge: String = "1080p",
    val progress: Float? = null
)

// ── SearchResult ──────────────────────────────────────────────────────────
enum class MediaType(val label: String) {
    MOVIE("סרט"),
    TV_SHOW("סדרה")
}

@Immutable
data class SearchResult(
    val id: String,
    val title: String,
    val posterUrl: String,
    val backdropUrl: String? = null,
    val logoUrl: String? = null,
    val type: MediaType,
    val rating: Float = 0f,
    val releaseYear: String = "",
    val overview: String = "",
    val matchScore: Int = 0,
    val dominantColor: String? = null,
    val genre: String = "",
    val qualityTag: String = ""
)

// ── Subtitle ───────────────────────────────────────────────────────────────────
@Immutable
data class Subtitle(
    val language: String,
    val url: String,
    val isAutoGenerated: Boolean
)