package com.luminastreams.tv.domain.model

import androidx.compose.runtime.Immutable

@Immutable
data class Subtitle(
    val language: String,
    val url: String, // או ByteArray אם זה מגיע מהזיכרון
    val isAutoGenerated: Boolean
)